"""initial domain schema

Revision ID: 2ce258d3ad54
Revises:
Create Date: 2026-07-22 15:52:48.660004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ce258d3ad54"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("before_data", sa.JSON(), nullable=True),
        sa.Column("after_data", sa.JSON(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_resource_id"), ["resource_id"], unique=False
        )

    op.create_table(
        "bot_users",
        sa.Column("telegram_user_id", sa.String(length=100), nullable=False),
        sa.Column("private_chat_id", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("first_source", sa.String(length=100), nullable=True),
        sa.Column("latest_source", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_interaction_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "notification_preference",
            sa.Enum(
                "ALL_UPDATES",
                "MAJOR_ONLY",
                "PAUSED",
                name="notification_preference",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "BLOCKED", "STOPPED", name="bot_user_status", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_users")),
        sa.UniqueConstraint("private_chat_id", name=op.f("uq_bot_users_private_chat_id")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_bot_users_telegram_user_id")),
    )
    op.create_table(
        "content_items",
        sa.Column(
            "content_type",
            sa.Enum(
                "GIFT_CODE",
                "WEBSITE_ANNOUNCEMENT",
                "NEW_GAME",
                "NEW_FEATURE",
                "DAILY_EVENT",
                "LUCKY_SPIN",
                "BANK_DELAY",
                "DEPOSIT_BONUS",
                "WELCOME_BONUS",
                "VIP_BONUS",
                "EMERGENCY_NOTICE",
                "INDUSTRY_CONTENT",
                name="content_type",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("gift_code", sa.String(length=256), nullable=True),
        sa.Column("reward_text", sa.String(length=200), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_reference", sa.String(length=200), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "WAITING_REVIEW",
                "APPROVED",
                "ARCHIVED",
                name="content_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
    )
    op.create_table(
        "media_assets",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "GIFT_CODE",
                "WEBSITE_ANNOUNCEMENT",
                "NEW_GAME",
                "NEW_FEATURE",
                "DAILY_EVENT",
                "LUCKY_SPIN",
                "BANK_DELAY",
                "DEPOSIT_BONUS",
                "WELCOME_BONUS",
                "VIP_BONUS",
                "EMERGENCY_NOTICE",
                "INDUSTRY_CONTENT",
                name="media_category",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("telegram_file_id", sa.String(length=512), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ENABLED", "DISABLED", name="media_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_table(
        "telegram_destinations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=100), nullable=False),
        sa.Column(
            "destination_type",
            sa.Enum(
                "CHANNEL",
                "GROUP",
                "TEST_CHANNEL",
                "TEST_GROUP",
                name="destination_type",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("source_code", sa.String(length=64), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("bot_can_post", sa.Boolean(), nullable=False),
        sa.Column("bot_can_edit", sa.Boolean(), nullable=False),
        sa.Column("bot_can_delete", sa.Boolean(), nullable=False),
        sa.Column("last_permission_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ENABLED", "DISABLED", name="destination_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_destinations")),
        sa.UniqueConstraint("source_code", name=op.f("uq_telegram_destinations_source_code")),
        sa.UniqueConstraint(
            "telegram_chat_id", name=op.f("uq_telegram_destinations_telegram_chat_id")
        ),
    )
    op.create_table(
        "campaigns",
        sa.Column("campaign_code", sa.String(length=80), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=True),
        sa.Column(
            "publish_mode",
            sa.Enum(
                "IMMEDIATE", "SCHEDULED", "TEST", name="publish_mode", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("display_timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "WAITING_APPROVAL",
                "APPROVED",
                "SCHEDULED",
                "SENDING",
                "PARTIALLY_SENT",
                "SENT",
                "FAILED",
                "CANCELLED",
                "VALIDATION_FAILED",
                name="campaign_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("approved_by", sa.String(length=100), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rendered_caption", sa.Text(), nullable=True),
        sa.Column("rendered_buttons", sa.JSON(), nullable=True),
        sa.Column("rendered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_campaigns_content_id_content_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media_assets.id"],
            name=op.f("fk_campaigns_media_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("campaign_code", name=op.f("uq_campaigns_campaign_code")),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaigns_content_id"), ["content_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_media_id"), ["media_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_campaigns_scheduled_at"), ["scheduled_at"], unique=False
        )

    op.create_table(
        "bot_events",
        sa.Column("bot_user_id", sa.String(length=36), nullable=True),
        sa.Column("campaign_id", sa.String(length=36), nullable=True),
        sa.Column("destination_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_user_id"],
            ["bot_users.id"],
            name=op.f("fk_bot_events_bot_user_id_bot_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_bot_events_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["telegram_destinations.id"],
            name=op.f("fk_bot_events_destination_id_telegram_destinations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_events")),
    )
    with op.batch_alter_table("bot_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_events_bot_user_id"), ["bot_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bot_events_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bot_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_bot_events_destination_id"), ["destination_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bot_events_event_type"), ["event_type"], unique=False)

    op.create_table(
        "campaign_buttons",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column(
            "button_type",
            sa.Enum(
                "COPY_CODE",
                "CLAIM_NOW",
                "DAILY_REWARDS",
                "CUSTOMER_SERVICE",
                "MORE_PROMOTIONS",
                "PLAY_NOW",
                "VIEW_DETAILS",
                "SPIN_NOW",
                name="button_type",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("target_url", sa.String(length=2000), nullable=True),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("tracking_code", sa.String(length=100), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_buttons_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_buttons")),
        sa.UniqueConstraint("campaign_id", "row_number", "position", name="button_position"),
    )
    with op.batch_alter_table("campaign_buttons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_buttons_campaign_id"), ["campaign_id"], unique=False
        )

    op.create_table(
        "campaign_destinations",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("destination_id", sa.String(length=36), nullable=False),
        sa.Column("placement_code", sa.String(length=64), nullable=False),
        sa.Column("start_parameter", sa.String(length=64), nullable=False),
        sa.Column("tracking_code", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ENABLED",
                "DISABLED",
                name="campaign_destination_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_destinations_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["telegram_destinations.id"],
            name=op.f("fk_campaign_destinations_destination_id_telegram_destinations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_destinations")),
        sa.UniqueConstraint("campaign_id", "destination_id", name="campaign_destination"),
        sa.UniqueConstraint("tracking_code", name=op.f("uq_campaign_destinations_tracking_code")),
    )
    with op.batch_alter_table("campaign_destinations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_destinations_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_campaign_destinations_destination_id"), ["destination_id"], unique=False
        )

    op.create_table(
        "message_deliveries",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("destination_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=100), nullable=False),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENDING",
                "SENT",
                "RETRYING",
                "FAILED",
                "CANCELLED",
                name="delivery_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_message_deliveries_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["telegram_destinations.id"],
            name=op.f("fk_message_deliveries_destination_id_telegram_destinations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_deliveries")),
        sa.UniqueConstraint("campaign_id", "destination_id", name="delivery_target"),
    )
    with op.batch_alter_table("message_deliveries", schema=None) as batch_op:
        batch_op.create_index("ix_delivery_ready", ["status", "next_attempt_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_message_deliveries_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_deliveries_destination_id"), ["destination_id"], unique=False
        )

    op.create_table(
        "tracking_events",
        sa.Column("campaign_id", sa.String(length=36), nullable=True),
        sa.Column("destination_id", sa.String(length=36), nullable=True),
        sa.Column("tracking_code", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("anonymous_visitor_id", sa.String(length=100), nullable=True),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_tracking_events_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["telegram_destinations.id"],
            name=op.f("fk_tracking_events_destination_id_telegram_destinations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_events")),
    )
    with op.batch_alter_table("tracking_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracking_events_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracking_events_destination_id"), ["destination_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracking_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracking_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracking_events_tracking_code"), ["tracking_code"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracking_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracking_events_tracking_code"))
        batch_op.drop_index(batch_op.f("ix_tracking_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_tracking_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_tracking_events_destination_id"))
        batch_op.drop_index(batch_op.f("ix_tracking_events_campaign_id"))

    op.drop_table("tracking_events")
    with op.batch_alter_table("message_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_deliveries_destination_id"))
        batch_op.drop_index(batch_op.f("ix_message_deliveries_campaign_id"))
        batch_op.drop_index("ix_delivery_ready")

    op.drop_table("message_deliveries")
    with op.batch_alter_table("campaign_destinations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_destinations_destination_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_destinations_campaign_id"))

    op.drop_table("campaign_destinations")
    with op.batch_alter_table("campaign_buttons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_buttons_campaign_id"))

    op.drop_table("campaign_buttons")
    with op.batch_alter_table("bot_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_bot_events_destination_id"))
        batch_op.drop_index(batch_op.f("ix_bot_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_bot_events_campaign_id"))
        batch_op.drop_index(batch_op.f("ix_bot_events_bot_user_id"))

    op.drop_table("bot_events")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_scheduled_at"))
        batch_op.drop_index(batch_op.f("ix_campaigns_media_id"))
        batch_op.drop_index(batch_op.f("ix_campaigns_content_id"))

    op.drop_table("campaigns")
    op.drop_table("telegram_destinations")
    op.drop_table("media_assets")
    op.drop_table("content_items")
    op.drop_table("bot_users")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_resource_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_actor_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
