"""private bot tracking and analytics

Revision ID: bf041b6707aa
Revises: 2ce258d3ad54
Create Date: 2026-07-22 16:19:45.059091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf041b6707aa"
down_revision: str | Sequence[str] | None = "2ce258d3ad54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "private_message_deliveries",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("bot_user_id", sa.String(length=36), nullable=False),
        sa.Column("private_chat_id", sa.String(length=100), nullable=False),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENDING",
                "SENT",
                "RETRYING",
                "FAILED",
                "CANCELLED",
                name="private_delivery_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_user_id"],
            ["bot_users.id"],
            name=op.f("fk_private_message_deliveries_bot_user_id_bot_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_private_message_deliveries_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_private_message_deliveries")),
        sa.UniqueConstraint("campaign_id", "bot_user_id", name="private_delivery_user"),
    )
    with op.batch_alter_table("private_message_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_private_delivery_ready", ["status", "next_attempt_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_private_message_deliveries_bot_user_id"), ["bot_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_private_message_deliveries_campaign_id"), ["campaign_id"], unique=False
        )

    op.create_table(
        "tracking_links",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("destination_id", sa.String(length=36), nullable=False),
        sa.Column("campaign_button_id", sa.String(length=36), nullable=False),
        sa.Column("tracking_code", sa.String(length=100), nullable=False),
        sa.Column("target_url", sa.String(length=2000), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ENABLED", "DISABLED", name="tracking_link_status", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_button_id"],
            ["campaign_buttons.id"],
            name=op.f("fk_tracking_links_campaign_button_id_campaign_buttons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_tracking_links_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["telegram_destinations.id"],
            name=op.f("fk_tracking_links_destination_id_telegram_destinations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_links")),
        sa.UniqueConstraint(
            "campaign_id",
            "destination_id",
            "campaign_button_id",
            name="tracking_link_placement_button",
        ),
        sa.UniqueConstraint("tracking_code", name=op.f("uq_tracking_links_tracking_code")),
    )
    with op.batch_alter_table("tracking_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracking_links_campaign_button_id"), ["campaign_button_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracking_links_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracking_links_destination_id"), ["destination_id"], unique=False
        )

    with op.batch_alter_table("bot_users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_test", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "priority",
                sa.Enum(
                    "NORMAL",
                    "MAJOR",
                    "EMERGENCY",
                    name="campaign_priority",
                    native_enum=False,
                    length=40,
                ),
                nullable=False,
                server_default="NORMAL",
            )
        )
        batch_op.add_column(
            sa.Column(
                "send_to_private_bot",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table("tracking_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tracking_link_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_tracking_events_tracking_link_id"), ["tracking_link_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_tracking_events_tracking_link_id_tracking_links"),
            "tracking_links",
            ["tracking_link_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracking_events", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_tracking_events_tracking_link_id_tracking_links"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_tracking_events_tracking_link_id"))
        batch_op.drop_column("tracking_link_id")

    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_column("send_to_private_bot")
        batch_op.drop_column("priority")

    with op.batch_alter_table("bot_users", schema=None) as batch_op:
        batch_op.drop_column("is_test")

    with op.batch_alter_table("tracking_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracking_links_destination_id"))
        batch_op.drop_index(batch_op.f("ix_tracking_links_campaign_id"))
        batch_op.drop_index(batch_op.f("ix_tracking_links_campaign_button_id"))

    op.drop_table("tracking_links")
    with op.batch_alter_table("private_message_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_private_message_deliveries_campaign_id"))
        batch_op.drop_index(batch_op.f("ix_private_message_deliveries_bot_user_id"))
        batch_op.drop_index("ix_private_delivery_ready")

    op.drop_table("private_message_deliveries")
    # ### end Alembic commands ###
