"""nexus content sync and audit security

Revision ID: c7e551b5f1e9
Revises: bf041b6707aa
Create Date: 2026-07-22 16:43:08.109152

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7e551b5f1e9"
down_revision: str | Sequence[str] | None = "bf041b6707aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_events",
        sa.Column("source_system", sa.String(length=50), nullable=False),
        sa.Column("external_event_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PROCESSED",
                "REJECTED",
                name="integration_event_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_integration_events_content_id_content_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_events")),
        sa.UniqueConstraint("source_system", "external_event_id", name="integration_event_source"),
    )
    with op.batch_alter_table("integration_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_integration_events_content_id"), ["content_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_integration_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_integration_events_received_at"), ["received_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("integration_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integration_events_received_at"))
        batch_op.drop_index(batch_op.f("ix_integration_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_integration_events_content_id"))

    op.drop_table("integration_events")
    # ### end Alembic commands ###
